### ISSUE TITLE
Install bat file missing from repo

### ISSUE THREAD

**Issue by mpmccauley** [irrer/aqa#1]
Hi there,

I wanted to check out this project. It seems interesting. I noticed the README references a batch file for installation that does not exist in the repo. Any suggestions?

Thanks!

**Comment by irrer** [comment]
Mike -

I'm assuming that you are referring to the AQA project.  

Note: If you want to use [DICOM+](https://github.com/irrer/DICOMClient#user-content-dicom-for) (a DICOM multitool, mostly for anonymizing/de-identifying) there is a zip file with pre-built jar and bat file you can just run.

Early in the project I had intended to write an installation file, but never did.  This is not the kind of project that lends itself to "a quick install to try it out", but...

There is an installation of it at: https://automatedqualityassurance.org/ that you are welcome to peruse.  Most of the site is password protected, but you can view the user guides.

The AQA platform is all about testing radiation treatment machines, mostly Varian TrueBeam.  We have an active consortium with radiation oncology departments around the world participating.  Our intention is to improve speed and efficacy, ultimately bringing that to the clinic.

If you are interested, we could zoom to discuss it further and give you a demonstration.  

Thanks,

- Jim
irrer@med.umich.edu

**Comment by mpmccauley** [comment]
Hey Jim,

Thanks for the quick response! Yes, I was referring to the AQA project. A friend recommended checking it out, so I figured I would reach out here. A brief demo could be interesting if you have the time. I think it makes more sense for me to reach out via email. I'll close this issue.

Thanks!
-Mike

**Comment by irrer** [comment]
Sounds good.

BTW - what institution are you with?  I'm at Michigan Medicine (Univ of Mich Ann Arbor).

- Jim

irrer@med.umich.edu

**Comment by mpmccauley** [comment]
Hey Jim - I'm with IBA Dosimetry on the QA equipment vendor side.
